# Generated by Django 4.0 on 2021-12-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='alias',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='hero',
            name='address',
            field=models.CharField(default=7031203995, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='total',
            field=models.CharField(default=5000, max_length=60),
            preserve_default=False,
        ),
    ]
